spring.application.name=bizflow

spring.datasource.url=jdbc:mysql://bizflow-mysql-bizflow123.h.aivencloud.com:24759/bizflow
spring.datasource.username=avnadmin
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

